#ifndef AUDIOPLUGINHOST_GLOBAL_H
#define AUDIOPLUGINHOST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AUDIOPLUGINHOST_LIBRARY)
#  define AUDIOPLUGINHOST_EXPORT Q_DECL_EXPORT
#else
#  define AUDIOPLUGINHOST_EXPORT Q_DECL_IMPORT
#endif

#endif // AUDIOPLUGINHOST_GLOBAL_H
